CREATE TABLE PC(
	PcID INTEGER PRIMARY KEY,
	Password TEXT NOT NULL,
	MAC TEXT NOT NULL UNIQUE,
	TimeUsage INTEGER
);

CREATE TABLE Admin(
	AdminID INTEGER PRIMARY KEY,
	Fullname TEXT NOT NULL,
	Phone TEXT, 
	Password TEXT NOT NULL
);

CREATE TABLE Bill(
	PcID INTEGER,
	DateAndTime datetime,
	Status INTEGER,
	AdminID INTEGER,
	PRIMARY KEY(PcID,DateAndTime),
	FOREIGN KEY(PcID)
		REFERENCES PC,
	FOREIGN KEY(AdminID)
		REFERENCES Admin
);

CREATE TABLE Items(
	ItemsID INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	Price INTEGER,
	Category TEXT
);

CREATE TABLE Cart(
	PcID INTEGER,
	DateAndTime datetime,
	ItemsID INTEGER,
	Amount INTEGER,
	PRIMARY KEY(PcID,DateAndTime),
	FOREIGN KEY(PcID,DateAndTime)
		REFERENCES Bill,
	FOREIGN KEY(ItemsID)
		REFERENCES Items
);