BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Bill" (
	"PcID"	INTEGER NOT NULL,
	"DateTime"	INTEGER NOT NULL,
	"Status"	INTEGER NOT NULL,
	"AdminID"	INTEGER NOT NULL,
	PRIMARY KEY("PcID","DateTime"),
	FOREIGN KEY("PcID") REFERENCES "PC"("PcID"),
	FOREIGN KEY("AdminID") REFERENCES "Admin"("AdminID")
);
CREATE TABLE IF NOT EXISTS "Admin" (
	"AdminID"	INTEGER NOT NULL,
	"Fullname"	TEXT NOT NULL,
	"Phone"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	PRIMARY KEY("AdminID")
);
CREATE TABLE IF NOT EXISTS "PC" (
	"PcID"	INTEGER NOT NULL,
	"Password"	INTEGER NOT NULL,
	"MAC"	INTEGER NOT NULL,
	"Time usage"	INTEGER NOT NULL,
	PRIMARY KEY("PcID")
);
CREATE TABLE IF NOT EXISTS "Items" (
	"ItemID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Price"	INTEGER NOT NULL,
	"Category"	TEXT NOT NULL,
	PRIMARY KEY("ItemID")
);
CREATE TABLE IF NOT EXISTS "Cart" (
	"PcID"	INTEGER NOT NULL,
	"DateTime"	INTEGER NOT NULL,
	"ItemID"	INTEGER NOT NULL,
	"Amount"	INTEGER NOT NULL,
	PRIMARY KEY("PcID","DateTime"),
	FOREIGN KEY("ItemID") REFERENCES "Items"("ItemID"),
	FOREIGN KEY("DateTime") REFERENCES "Bill"("DateTime"),
	FOREIGN KEY("PcID") REFERENCES "PC"("PcID")
);
COMMIT;
